### ISSUE TITLE
好像不兼容 vue 2.6.14版本

### ISSUE THREAD

**Issue by CodeZealot1024** [CarterLi/vue3-ace-editor#10]
![image](https://user-images.githubusercontent.com/46394426/124745989-fa9f7a80-df52-11eb-8722-7f7899f473df.png)
这个defineComponent不存在
按道理来说应该要兼容一下的

**Comment by CarterLi** [comment]
> 按道理来说应该要兼容一下的

按哪个道理？

**Comment by wangxiang4** [comment]
我把你的重写了,全部用JS学的,你这个vue2.x版本会有问题
