### ISSUE TITLE
how to enable json-worker

### ISSUE THREAD

**Issue by mattsouth** [CarterLi/vue3-ace-editor#12]
issue #3 suggests that to add validation feedback you need to:
1. load the appropriate worker
2. set the appropriate component option

Im trying to get validation feedback for a json editor so I gather I should import the json-worker alongside the mode and theme, i.e.

```javascript
import 'ace-builds/src-noconflict/mode-json';
import 'ace-builds/src-noconflict/theme-textmate';
import 'ace-builds/src-noconflict/worker-json';
```
however if I do this then the vue-cli tells me:

```
warning  in ./node_modules/ace-builds/src-noconflict/worker-json.js

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

 warning  in ./node_modules/ace-builds/src-noconflict/worker-json.js

Critical dependency: the request of a dependency is an expression
```
Have you got any hints as to what I'm doing wrong?

**Comment by inspire-lives** [comment]
> 

I hava some problems when import the worker.
![image](https://user-images.githubusercontent.com/93400222/146548093-d80692c1-1294-48c0-8d75-4ae032a09569.png)

**Comment by cyccess** [comment]
@inspire-lives 
![image](https://user-images.githubusercontent.com/5134209/148900804-ceaa638d-41a9-4b23-b657-1085517c811d.png)
import this line of code and it will work!
you see 
https://github.com/ajaxorg/ace-builds/blob/a4103cb0a672a4fec9a16fc344f3116b51d6bcda/webpack-resolver.js#L241

**Comment by CarterLi** [comment]
> @inspire-lives ![image](https://user-images.githubusercontent.com/5134209/148900804-ceaa638d-41a9-4b23-b657-1085517c811d.png) import this line of code and it will work! you see [ajaxorg/ace-builds@`a4103cb`/webpack-resolver.js#L241](https://github.com/ajaxorg/ace-builds/blob/a4103cb0a672a4fec9a16fc344f3116b51d6bcda/webpack-resolver.js#L241)

You don't want to use `webpack-resolver` unless you can accept this issue: https://github.com/CarterLi/vue3-ace-editor/issues/3
