### ISSUE TITLE
Editor does not appear

### ISSUE THREAD

**Issue by seijikohara** [CarterLi/vue3-ace-editor#2]
## Environment
- Vue 3.0.2
- Chrome 86.0.4240.80

## Problem

I created a component using `vue3-ace-editor` as follows.

```vue
<template>
  <div style="height: 100vh; width: 100vw;">
    <VAceEditor v-model="state.content" lang="html" theme="chrome" />
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive } from "vue";
import { VAceEditor } from "vue3-ace-editor";

export default defineComponent({
  name: "Editor",
  components: { VAceEditor },
  setup() {
    const state = reactive({
      content: "content text"
    });
    return {
      state
    };
  }
});
</script>
```

However, the editor is not shown on the screen when this component is shown.
The console shows Waning.

![image](https://user-images.githubusercontent.com/9543980/96732670-9011d300-13f3-11eb-90b5-65e598483e15.png)

Please let me know if there are any errors in usage.
All the code is here.
https://github.com/seijikohara/test-vue3-ace-editor

**Comment by CarterLi** [comment]
`v-model:value="content"`

**:value**

**Comment by seijikohara** [comment]
It doesn't work.

`v-model:value="value="content"` outputs a warning to the console, but no editor is shown.
![image](https://user-images.githubusercontent.com/9543980/96759040-78961280-1412-11eb-8b3a-35a45f8cfdbd.png)

`v-model:value="state.content"` does not output a warning, but the editor is not shown.

**Comment by CarterLi** [comment]
specify the height using `style="height: xxxpx"`

**Comment by seijikohara** [comment]
> specify the height using `style="height: xxxpx"`

It worked!
This problem is solved.
Thank you for your help.
