### ISSUE TITLE
按照文档启用代码提示失败

### ISSUE THREAD

**Issue by musen123** [CarterLi/vue3-ace-editor#23]
在组件中添加
import ace from 'ace-builds';
import workerJsonUrl from 'ace-builds/src-noconflict/worker-json.js'; // For webpack / vue-cli
ace.config.setModuleUrl('ace/mode/json_worker', workerJsonUrl);
之后，控制台报错
```
15ea4934-fc78-46f4-8918-e72928a64c4d:1 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8080/[object%20Object]' failed to load.
    at blob:http://localhost:8080/15ea4934-fc78-46f4-8918-e72928a64c4d:1:1
```

**Comment by CarterLi** [comment]
file-loader?esModule=false!
