### ISSUE TITLE
请问js代码要怎么初始化设置进去

### ISSUE THREAD

**Issue by QDasia** [CarterLi/vue3-ace-editor#24]
比如说我有个函数，怎样才能放到编辑器中，用JSON.stringify的时候也是undefined，直接toString转成字符串的时候，又没有编辑器的格式
![image](https://user-images.githubusercontent.com/31614680/173273594-78147d09-ede1-4325-bff0-adfc87a04642.png)
![image](https://user-images.githubusercontent.com/31614680/173273622-06e87e7a-b0ec-412b-8858-d3af95290302.png)

**Comment by CarterLi** [comment]
直接赋值字符串不好么
