### ISSUE TITLE
A lot of files are created during project build

### ISSUE THREAD

**Issue by n-skryabin** [CarterLi/vue3-ace-editor#3]
After adding this package to the project, a lot of files are created during build. (npm run build)
![Screenshot_2](https://user-images.githubusercontent.com/22622770/105749285-decb8d80-5f4b-11eb-9d6f-31c6be03e5bf.png)
As you can see, each of these files is responsible for a separate topic, mode, etc. for the ace editor component. 
![Screenshot_3](https://user-images.githubusercontent.com/22622770/105749321-e8ed8c00-5f4b-11eb-9130-f81b17134304.png)
How do I make all these files part of the assembly? In my situation, I don't need lazy loading of these modules. Thank you.

**Comment by CarterLi** [comment]
Well yes.
These files are generated by `ace-builds/webpack-resolver` which is necessary for dynamic mode/theme loading support. I was considering removing it, but it's a breaking change.

**Comment by n-skryabin** [comment]
Thank you very much!!! It works! Just great! The only thing is that the "on-the-fly" validation has disappeared. To enable validation, should I also import a package?
![Screenshot_4](https://user-images.githubusercontent.com/22622770/105823895-6655e280-5fc6-11eb-8b7e-21cb3344541a.png)

For example, this is how it looks.
![Screenshot_5](https://user-images.githubusercontent.com/22622770/105824036-8be2ec00-5fc6-11eb-9e4e-5ae86e42ce45.png)

**Comment by n-skryabin** [comment]
@CarterLi Thank you very much!!! It works! Just great! The only thing is that the "on-the-fly" validation has disappeared. To enable validation, should I also import a package?

**Comment by n-skryabin** [comment]
@CarterLi Thank you very much!!! It works! Just great! The only thing is that the "on-the-fly" validation has disappeared. To enable validation, should I also import a package?
![Screenshot_4](https://user-images.githubusercontent.com/22622770/105824325-de240d00-5fc6-11eb-9847-40498e899ca0.png)

For example, this is how it looks.
![Screenshot_5](https://user-images.githubusercontent.com/22622770/105824377-ed0abf80-5fc6-11eb-8017-b8c49410869d.png)

**Comment by CarterLi** [comment]
It relies on `javascript-worker`.

Worker support is disabled by default, you may enable it with `:options="{ useWorker: true }"`

To import the worker file, see: https://github.com/ajaxorg/ace-builds/blob/a4103cb0a672a4fec9a16fc344f3116b51d6bcda/webpack-resolver.js#L240

**Comment by n-skryabin** [comment]
@CarterLi Thank you!!! I fixed it this way

`import ace from 'ace-builds';
ace.config.set(
    "basePath", 
    "https://cdn.jsdelivr.net/npm/ace-builds@" + require('ace-builds').version + "/src-noconflict/"
)`

**Comment by n-skryabin** [comment]
@CarterLi Thank you!!! I fixed it this way.

`import ace from 'ace-builds';
ace.config.set(
     "basePath", 
     "https://cdn.jsdelivr.net/npm/ace-builds@" + require('ace-builds').version + "/src-noconflict/"
)`

**Comment by n-skryabin** [comment]
@CarterLi Thank you!!! I fixed it this way.

```
    import ace from 'ace-builds';
    ace.config.set(
        "basePath", 
        "https://cdn.jsdelivr.net/npm/ace-builds@" + require('ace-builds').version + "/src-noconflict/")
```

**Comment by rahulkumarsingh73690** [comment]
vue3-ace-editor.js:1160 Unable to infer path to ace from script src, use ace.config.set('basePath', 'path') to enable dynamic loading of modes and themes or with webpack use ace/webpack-resolver
