### ISSUE TITLE
这个支持js代码输入提示

### ISSUE THREAD

**Issue by 13371826981** [CarterLi/vue3-ace-editor#33]
![image](https://user-images.githubusercontent.com/20837054/198561166-2851f17f-47c7-4c14-9357-fa29354c44c9.png)
我看这个是可以的

**Comment by CarterLi** [comment]
那估计要另外的插件

**Comment by CarterLi** [comment]
Added example for autocompletion

https://github.com/CarterLi/vue3-ace-editor/commit/743c420f60f41300b4db736ed2f5ddae70341a34#diff-874cfb118e71629fda9c2b540e3a12e21de068f6dde084ff36fbfa1ff18467ddR19
