### ISSUE TITLE
[Vue3.2.41]无法显示错误提示

### ISSUE THREAD

**Issue by un-hum** [CarterLi/vue3-ace-editor#36]
如题，把demo代码拉回～运行后，依旧没有错误提示。
是vue版本的问题吗？

**Comment by un-hum** [comment]
另外，有钩子可以把错误提示emit出来吗

**Comment by CarterLi** [comment]
> 如题，把demo代码拉回～运行后，依旧没有错误提示。 是vue版本的问题吗？

演示代码正常哎，你在自己找找问题吧

**Comment by CarterLi** [comment]
> 另外，有钩子可以把错误提示emit出来吗

没有，你需要自己研究一下ace
