### ISSUE TITLE
如何获取编辑器选中的内容？

### ISSUE THREAD

**Issue by yplove156** [CarterLi/vue3-ace-editor#37]
如题，未发现组件有获取选中内容的方式

**Comment by yplove156** [comment]
已解决：
`let selectionRange = this.$refs.sqlEditor._editor.session.getTextRange(this.$refs.sqlEditor._editor.getSelectionRange())
      console.log(selectionRange)`

**Comment by CarterLi** [comment]
不应该用getSelectedText？
