### ISSUE TITLE
Trying to use this with Nuxt and have errors

### ISSUE THREAD

**Issue by vedmant** [CarterLi/vue3-ace-editor#38]
There are number of errors I have in console:

e3-ace-editor.js:1109 Unable to infer path to ace from script src, use ace.config.set('basePath', 'path') to enable dynamic loading of modes and themes or with webpack use ace/webpack-resolver
r

caught SyntaxError: Unexpected token '<' (at VM3758 mode-html.js:1:1)
caught SyntaxError: Unexpected token '<' (at VM3759 theme-chrome.js:1:1)
caught Error: couldn't load module ace/theme/chrome or it didn't call define
 t afterLoad (vue3-ace-editor.js:19101:1)
    at vue3-ace-editor.js:1079:1
    at Array.forEach (<anonymous>)
    at vue3-ace-editor.js:1078:1
    at vue3-ace-editor.js:1122:1
    at _require (vue3-ace-editor.js:59:1)
    at req (vue3-ace-editor.js:97:1)
    at vue3-ace-editor.js:1121:1
    at afterLoad (vue3-ace-editor.js:1074:1)
    at s.onload.s.onreadystatechange (vue3-ace-editor.js:711:1)

Just followed basic instructions:

```vue
<template>
  <VAceEditor v-model="code" lang="html" :min-lines="10" />
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { VAceEditor } from 'vue3-ace-editor'

export default defineComponent({
  components: { VAceEditor },

  data: () => ({
    code: '',
  }),
})
</script>
```

**Comment by CarterLi** [comment]
You must import modes and themes yourself. See https://github.com/CarterLi/vue3-ace-editor#breaking-change

**Comment by vedmant** [comment]
@CarterLi I see, that has to be in "How to use" section, otherwise people would assume that "How to use" instructions supposed to work as is.
