### ISSUE TITLE
editor.undo，获取当前的撤回之

### ISSUE THREAD

**Issue by pangchao21** [CarterLi/vue3-ace-editor#42]
editor.undo()，能获取到当前要撤回值，因为在后台返回的数据之后添加的值才可以撤回，不然就不给撤回

**Comment by CarterLi** [comment]
你看得懂你在说什么吗？

**Comment by pangchao21** [comment]
如: select * as from xxx ; 我在select * as from xxx的后面换行输入了abc;我快捷键ctrl+z撤回了abc,当编辑器内容只剩select * as from xxx，就不能继续撤回了

**Comment by CarterLi** [comment]
我用demo页面测试了一下，没复现
https://carterli.github.io/vue3-ace-editor/

**Comment by pangchao21** [comment]
<img width="1354" alt="image" src="https://github.com/CarterLi/vue3-ace-editor/assets/25843968/1f63b18f-2c24-49be-977c-35ade0d41823">
<img width="1376" alt="image" src="https://github.com/CarterLi/vue3-ace-editor/assets/25843968/5f90a391-40c1-4fa6-9612-f0fdc16c769e">
第一张图直接打开有很多内容，然后我按ctrl+z会清空掉所有的值了。期望就是第一次赋值的内容不能被撤回

**Comment by CarterLi** [comment]
你监听一下值的变化，如果被清空了再强制赋值回去不行么

**Comment by pangchao21** [comment]
有道理，也能实现，可能会闪一下，就想有没更优解决方案,  -_-
