### ISSUE TITLE
vue3-ace-editor do not work on uni-app ide.

### ISSUE THREAD

**Issue by fynnchai** [CarterLi/vue3-ace-editor#43]
Copy the codes in the vue page in uniapp ide (vue2, vue3.I user the vue3), there will be same compile error.

I wish it will work on the uni-app platform.

**Comment by fynnchai** [comment]
Cannot read property 'ace' of undefined

**Comment by CarterLi** [comment]
I don't think ace-editor works in uni-app

**Comment by fynnchai** [comment]
Thank you for your reply 😊

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Carter ***@***.***>
发送时间: 2023年9月27日 15:08
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [CarterLi/vue3-ace-editor] vue3-ace-editor do not work on uni-app ide. (Issue #43)


I don't think ace-editor works in uni-app
