### ISSUE TITLE
placeholder porp not work

### ISSUE THREAD

**Issue by kanbang** [CarterLi/vue3-ace-editor#44]
placeholder porp not work
`
<v-ace-editor v-model:value="ace_states.content" :readonly="false" @init="onAceInit"
                        @change="onAceChange" :lang="ace_states.lang" :theme="ace_states.theme"
                        :placeholder="'Enter Formily Schema ...'" :options="{
                            useWorker: true,
                            enableBasicAutocompletion: true,
                            enableSnippets: true,
                            enableLiveAutocompletion: true,
                        }" style="height: 100%" />
                </div>
`

**Comment by CarterLi** [comment]
Filed a bug upstream. Please wait for their fix.

https://github.com/ajaxorg/ace/issues/5361
