### ISSUE TITLE
Nuxt 3.8.0 (Not working)

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [CarterLi/vue3-ace-editor#45]
vue3-ace-editor.js:1160 Unable to infer path to ace from script src, use ace.config.set('basePath', 'path') to enable dynamic loading of modes and themes or with webpack use ace/webpack-resolver

ace.client.js - https://goonlinetools.com/snapshot/code/#sji4jbt7kgv8c2rebagiq

**Comment by CarterLi** [comment]
Try `import 'ace-build'` before importing `vue3-ace-editor`

**Comment by CarterLi** [comment]
Follow the example please: https://github.com/CarterLi/vue3-ace-editor#use-it-with-nuxt
