### ISSUE TITLE
min-lines and max-lines not working

### ISSUE THREAD

**Issue by sagoncalves** [CarterLi/vue3-ace-editor#5]
I want the editor to grow as many lines up to 8 or infinity but both doesn't work. 

This example code doesn't display anything as the editor has no height set, but as far i've seen it should work.

Example: 
```html
<v-ace-editor  placeholder="'code here'"
    v-model:value="code" 
    min-lines="3"
    max-lines="8"
    lang="javascript"
    theme="chrome" :wrap='true'
    />
```

**Comment by CarterLi** [comment]
We didn't provide such properties before, you may specify it with `:options="{ minLines: 3, maxLines: 5 }"`

I agree that `min-lines` and `max-lines` are useful and can be better then specifying height. I'll provide these properties as shortcuts.

**Comment by sagoncalves** [comment]
@CarterLi thanks!!
