### ISSUE TITLE
hope to support vue 2.7

### ISSUE THREAD

**Issue by defghy** [CarterLi/vue3-ace-editor#50]
vue 2.7 don't have `capitalize` function

vue2-ace-editor use require which is not support vite

**Comment by CarterLi** [comment]
As said in the repo title, it's **vue3**-ace-editor

**Comment by defghy** [comment]
Got it

In case someone use vue2.7 && vite
I publish this npm lib
[vue2.7-ace-editor](https://www.npmjs.com/package/vue2.7-ace-editor)
