### ISSUE TITLE
Cannot load language mode files (for syntax highlighting)

### ISSUE THREAD

**Issue by radiantone** [CarterLi/vue3-ace-editor#54]
The component tries to load js files from ace-builds at runtime, but they don't exist. Vite does not try to build these files into its pack.

When I copy them from the ace-builds node_modules location to my public url for my app, it says "define is not defined". Because these are AMD files not compatible with Vue3/Vite. Workarounds?

from mode-python.js

define("ace/mode/python_highlight_rules",["require","exports","module","ace/lib/oop","ace/mode/text_highlight_rules"], function(require, exports, module){/*
 * TODO: python delimiters
 */
"use strict";
var oop = require("../lib/oop");
var TextHighlightRules = require("./text_highlight_rules").TextHighlightRules;
var PythonHighlightRules = function () {
    var keywords = ("and|as|assert|break|class|continue|def|del|elif|else|except|exec|" +

**Comment by CarterLi** [comment]
Did you read the [doc](https://github.com/CarterLi/vue3-ace-editor?tab=readme-ov-file#load-modes-and-themes-required)?

**Comment by CarterLi** [comment]
import `vue3-ace-editor` or `ace-builds` before ace modes, which define the global variable `ace`

**Comment by CarterLi** [comment]
> Because these are AMD files not compatible with Vue3/Vite.

It has nothing to do with AMD. The code reads `ace.define()` but not `define()`

**Comment by radiantone** [comment]
![image](https://github.com/CarterLi/vue3-ace-editor/assets/25509097/fa0ba5c8-e6d8-40c8-8c1c-c96d4e20d8ba)

**Comment by CarterLi** [comment]
You must use `src-noconflict` instead of `src`

**Comment by radiantone** [comment]
I don't load the files. The package does. I have no idea how it tries to do it. But it doesn't work.

**Comment by radiantone** [comment]
Oh, you mean in the node path  node_modules/ace-builds/src-noconflict/. Got it. Will try using those.
