### ISSUE TITLE
Cannot disable ace worker

### ISSUE THREAD

**Issue by ZackStone** [CarterLi/vue3-ace-editor#55]
I'm getting this error when the component is being mounted:

Refused to create a worker from 'blob:http://localhost:50864/8038195d-1ff6-4dc2-a5bd-224b0263fb57' because it violates the following Content Security Policy directive: "child-src 'self'". Note that 'worker-src' was not explicitly set, so 'child-src' is used as a fallback.

And I don't want to enable that directive for security reasons.
I've searched a little bit and found two options that maybe can help to mitigate the error: "useWorker" and "loadWorkerFromBlob".
I think I can disable the worker, since I'm using the component just to give some color highlighting to a XML field.

![image](https://github.com/CarterLi/vue3-ace-editor/assets/9125490/813c665c-4e16-4004-b5d5-de3e4a3b9135)

![image](https://github.com/CarterLi/vue3-ace-editor/assets/9125490/ce96f880-d854-43e4-ba32-e6c201b2e7f8)

I noticed that your component is already setting the flag to false, so I don't know if there's something missing:
![image](https://github.com/CarterLi/vue3-ace-editor/assets/9125490/cf8ff2ab-9de8-4de3-aeae-f9d34b17e069)

Thanks in advance, great work by the way.

**Comment by CarterLi** [comment]
`useWorker: false` should work. It works to me at least.

`loadWorkerFromBlob` should be used as `ace.config.set('loadWorkerFromBlob', false);`. It's not necessary in your case since worker should have been disabled entirely by `useWorker: false`

**Comment by CarterLi** [comment]
If you think there are bugs, you should create a minimal reproduce repo.

**Comment by ZackStone** [comment]
> If you think there are bugs, you should create a minimal reproduce repo.

I tried to create a minimal app to repro, but it worked. Maybe there's something in the original project, that is legacy. Thanks for your answer.
