### ISSUE TITLE
[bug提交]问题描述：editor.getSession().setMode(langXXX)会报错net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by H4CKE3** [CarterLi/vue3-ace-editor#57]
每次第一次editor.getSession().setMode(langXXX)的时候 都会报错

 http://localhost:3000/problem/snippets/java.js net::ERR_ABORTED 404 (Not Found)
exports2.loadScript @ ace.js:804
load @ ace.js:1281
exports2.loadModule @ ace.js:1299
loadSnippetFile @ ext-language_tools.js:2472
loadSnippetsForMode @ ext-language_tools.js:2464
onChangeMode @ ext-language_tools.js:2455
EventEmitter._emit.EventEmitter._dispatchEvent @ ace.js:867
Editor2.onChangeMode @ ace.js:14319
EventEmitter._emit.EventEmitter._dispatchEvent @ ace.js:867
EditSession2.$onChangeMode @ ace.js:10436
(匿名) @ ace.js:10404
(匿名) @ ace.js:1275
(匿名) @ ace.js:1274
(匿名) @ ace.js:1330
_require @ ace.js:88
req @ ace.js:138
(匿名) @ ace.js:1329
loader @ ace.js:1240
afterLoad @ ace.js:1268
s.onload.s.onreadystatechange @ ace.js:809
load(异步)
exports2.loadScript @ ace.js:805
load @ ace.js:1281
exports2.loadModule @ ace.js:1299
EditSession2.setMode @ ace.js:10392
(匿名) @ AceEditor.vue:61
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
job @ runtime-core.esm-bundler.js:6096
callWithErrorHandling @ runtime-core.esm-bundler.js:195
flushJobs @ runtime-core.esm-bundler.js:409
Promise.then(异步)
queueFlush @ runtime-core.esm-bundler.js:319
queueJob @ runtime-core.esm-bundler.js:313
scheduler @ runtime-core.esm-bundler.js:6117
resetScheduling @ reactivity.esm-bundler.js:262
triggerEffects @ reactivity.esm-bundler.js:306
triggerRefValue @ reactivity.esm-bundler.js:1071
set value @ reactivity.esm-bundler.js:1118
set @ reactivity.esm-bundler.js:1136
_createVNode.onUpdate:modelValue._cache.<computed>._cache.<computed> @ AceEditor.vue:160
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
emit @ runtime-core.esm-bundler.js:726
(匿名) @ runtime-core.esm-bundler.js:7820
handleOptionSelect @ useSelect.ts:418
selectOptionClick @ option.vue:108
(匿名) @ option.vue:10
cache.<computed>.cache.<computed> @ runtime-dom.esm-bundler.js:1472
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
invoker @ runtime-dom.esm-bundler.js:693
显示 48 更多框架
显示简略信息

第一次报错 但是不影响功能 在不刷新页面的情况下第二次切换该语言 就不会报错
功能都正常 代码高亮也是语言相对应的高亮

**Comment by CarterLi** [comment]
You must provide a reproduce repo.
