### ISSUE TITLE
How to change language dynamicly? Is there any **changelang()** method,or anything like this?

### ISSUE THREAD

**Issue by mocheng520** [CarterLi/vue3-ace-editor#7]
****

**Comment by mocheng520** [comment]
or it only can be setted in Initializing,and I'm just waste of time

**Comment by CarterLi** [comment]
https://github.com/CarterLi/vue3-ace-editor/blob/master/index.js#L114

**Comment by mocheng520** [comment]
> https://github.com/CarterLi/vue3-ace-editor/blob/master/index.js#L114

please tell me what should I do? I can not understand that docu

**Comment by mocheng520** [comment]
> https://github.com/CarterLi/vue3-ace-editor/blob/master/index.js#L114

I've read vue2 document,now all my problems gone😁

**Comment by YiFo0315** [comment]
How did you solve this problem? I also encountered this problem recently.
